logging:
  level:
    felipetvsouza.github.micrometertryout: DEBUG
    reactor: WARN
    org.springframework: WARN

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric